prelude: :gerbil/compiler/ssxi
package: jafourni/gerbil-postgres

(begin
  (declare-type
   jafourni/gerbil-postgres/cursor#call-with-cursor
   (@lambda 6
            #f
            signature:
            (return:
             t::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/cursor)))
  (declare-type
   jafourni/gerbil-postgres/cursor#in-pg-cursor__%__%
   (@lambda 5
            #f
            signature:
            (return:
             std/iter#iterator::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/cursor)))
  (declare-type
   jafourni/gerbil-postgres/cursor#in-pg-cursor__%__0
   (@lambda 4
            #f
            signature:
            (return:
             std/iter#iterator::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/cursor)))
  (declare-type
   jafourni/gerbil-postgres/cursor#in-pg-cursor__%
   (@case-lambda
    (4
     jafourni/gerbil-postgres/cursor#in-pg-cursor__%__0
     signature:
     (return:
      std/iter#iterator::t
      effect:
      #f
      arguments:
      #f
      unchecked:
      #f
      origin:
      jafourni/gerbil-postgres/cursor))
    (5
     jafourni/gerbil-postgres/cursor#in-pg-cursor__%__%
     signature:
     (return:
      std/iter#iterator::t
      effect:
      #f
      arguments:
      #f
      unchecked:
      #f
      origin:
      jafourni/gerbil-postgres/cursor))))
  (declare-type
   jafourni/gerbil-postgres/cursor#in-pg-cursor__@
   (@kw-lambda-dispatch
    (fetch-size:)
    jafourni/gerbil-postgres/cursor#in-pg-cursor__%))
  (declare-type
   jafourni/gerbil-postgres/cursor#in-pg-cursor
   (@kw-lambda (fetch-size:) jafourni/gerbil-postgres/cursor#in-pg-cursor__@)))
