prelude: :gerbil/compiler/ssxi
package: jafourni/gerbil-postgres

(begin
  (declare-type
   jafourni/gerbil-postgres/errors#pg-error-fields
   (@lambda 1
            #f
            signature:
            (return:
             t::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-error-field
   (@lambda 2
            #f
            signature:
            (return:
             t::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-error-sqlstate
   (@lambda 1
            #f
            signature:
            (return:
             t::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-error-severity
   (@lambda 1
            #f
            signature:
            (return:
             t::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-error-detail
   (@lambda 1
            #f
            signature:
            (return:
             t::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-error-hint
   (@lambda 1
            #f
            signature:
            (return:
             t::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-error-position
   (@lambda 1
            #f
            signature:
            (return:
             t::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-error-constraint
   (@lambda 1
            #f
            signature:
            (return:
             t::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-error-table
   (@lambda 1
            #f
            signature:
            (return:
             t::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-error-column
   (@lambda 1
            #f
            signature:
            (return:
             t::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-sqlstate-class?
   (@lambda 2
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-sqlstate=?
   (@lambda 2
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-connection-error?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-integrity-violation?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-unique-violation?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-foreign-key-violation?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-not-null-violation?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-check-violation?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-serialization-failure?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-deadlock?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-syntax-error?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-insufficient-privilege?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-undefined-table?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-undefined-column?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors)))
  (declare-type
   jafourni/gerbil-postgres/errors#pg-transient-error?
   (@lambda 1
            #f
            signature:
            (return:
             boolean::t
             effect:
             #f
             arguments:
             #f
             unchecked:
             #f
             origin:
             jafourni/gerbil-postgres/errors))))
