(declare (block) (standard-bindings) (extended-bindings))
(begin
  (begin
    (load-module "std/db/dbi")
    (load-module "std/db/postgresql")
    (load-module "jafourni/gerbil-postgres/errors")
    (load-module "jafourni/gerbil-postgres/types")
    (load-module "jafourni/gerbil-postgres/logging")
    (load-module "jafourni/gerbil-postgres/query")
    (load-module "jafourni/gerbil-postgres/pool")
    (load-module "jafourni/gerbil-postgres/retry")
    (load-module "jafourni/gerbil-postgres/transactions")
    (load-module "jafourni/gerbil-postgres/cursor")
    (load-module "jafourni/gerbil-postgres/migrations"))
  (load-module "jafourni/gerbil-postgres/main~0"))
